algoritmo "pgm13"
// Função :  criar 1 ou 2 variáveis atribuindo valores e exibir a operação
//           de exponenciação
// Autor :   MATHEUS TOMAZ DA SILVA
// Data : 21/01/2021
// Seção de Declarações 
var
   res: real
inicio
      //atribuindo valores e operação de conta
        res<- 4 ^ 3
        
      // Exibindo para o usuário
         escreva("O resultado da operação usando expoente é: ", res)

fimalgoritmo
