algoritmo "pgm15"
// Função : Receber um valor e monstar o antecessor
// Autor :  MATHEUS TOMAZ DA SILVA
// Data : 21/01/2021

var
   num1, res: real
inicio

      // Recebendo a informação do usuário
         escreva ("Informe num 1: ")
         leia (num1)

      //efetuando a operação e exibindo para o usuário
        res<- num1 - 1
        escreva("O numero antecessor ao indicado é: ", res)
fimalgoritmo
