algoritmo "pgm30"
// Função : Ler temperatura em CELSIUS e exibir em FAHRENHEIT
// Autor :  Matheus Tomaz da Silva
// Data : 24/01/2021

var
   C: real
inicio
     // Recebendo dados do usuário
         escreva ("Digite a temperatura em graus CELSIUS: ")
         leia (C)

      // exibindo para o usuário
         escreval ("")
         escreval ("TEMPERATURA:", ((C * 1.8) + 32), "°FAHRENHEIT")
fimalgoritmo
